### PR TITLE
Update pwpolicy_custom_regex_enforce.yaml

### PR DESCRIPTION
**Pull request by ion-ize**
Changed the recommended custom regex to require 1 capitol and 1 lowercase letter anywhere in the password. The previous regex required a capital letter immediately followed by a lowercase letter or it would not match.

### CODE REVIEW

**Comment by robertgendler** [comment]
@Crimsonize we recently updated that rule on the Sonoma branch. Can you see if your PR is still required or update it potentially if need be?

**Comment by Crimsonize** [comment]
@robertgendler I updated the PR to not conflict with the recent changes, and yes, it is still required.

**Comment by Crimsonize** [comment]
@robertgendler yes this would resolve [#358](https://github.com/usnistgov/macos_security/issues/358).

**Comment by robertgendler** [comment]
Awesome!

**Pull request merged**
