### PR TITLE
change removal of public ssh key file

### PR DESCRIPTION
**Pull request by timnottom**
The file created was a .pub file so the removal should be .pub and not .public

I kept getting errors when running my generated audit script from Jamf. The script is trying to remove a file by doing `/bin/rm /etc/ssh/ssh_host_rsa_key.public` but i get a "No such file or directory".
When I run the command that is creating the ssh_host_rsa_key by doing `/usr/bin/ssh-keygen -q -N "" -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key` the result is 2 files: `/etc/ssh/ssh_host_rsa_key` and `/etc/ssh/ssh_host_rsa_key.pub`
The created file is a **.pub** in stead of **.public**.
When I change the `/bin/rm /etc/ssh/ssh_host_rsa_key.public` into `/bin/rm /etc/ssh/ssh_host_rsa_key.pub` the file gets deleted.
Screenshot 2023-08-03 at 14 45 02

### CODE REVIEW

**Comment by vaughnhart** [comment]
dot those Is and cross those Ts (like crosshairs)!

**Comment by timnottom** [comment]
@vaughnhart Not a native speaker here, but I'm guessing that this is positive? 😅 If something is needed to change on my PR, let me know!

**Comment by vaughnhart** [comment]
@timnottom yes, it's an old expression with a twist that means the devil is in the details and I'd add that's true especially on Unix/Linux/command line-bases operating systems (OS). Switches, paths, daemons and extensions can change with almost every major version of an OS. Assuming x means y and z is wide open. Great find Tim!

**Comment by timnottom** [comment]
Thanks @vaughnhart!

**Pull request merged**
